version: '2'
services:
    mysql_database:
        container_name: mysqlUsuarios
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        command: [nginx-debug, '-g', 'daemon off;']
        links:
            - usuarios
            - inventarios
        ports:
            - "8080:80"
    usuarios:
        build: ./usuarios

    inventarios:
        build: ./inventarios