version: '2'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        command: [nginx-debug, '-g', 'daemon off;']
        links:
            - usuarios
            - inventarios
        ports:
            - "8080:80"
        
    usuarios:
        build: ./usuarios

    inventarios:
        build: ./inventarios